#pragma once

#include <iostream>
#include <string>
#include <vector>
#include <memory>
#include <array>
#include <algorithm>
#include <stdexcept>
#include <utility>
#include <fstream>
#include <unordered_map>
#include <unordered_set>
#include <map>
#include <cstddef>
#include <functional>
#include <string_view>
#include <cmath>
#include <iterator>
#include <iomanip>
#include <thread>
#include <atomic>
#include <cassert>
#include <optional>
#include <any>
#include <climits>
#include <random>
#include <cstdint>
#include <cstring>
#include <cstdlib>
#include <ctime>
#include <cstdio>
