#pragma once

// Keyboard key and mouse button definitions

namespace sm::internal {
    enum class Key {
        Unknown,
        Return,
        Escape,
        Backspace,
        Tab,
        Space,
        Exclaim,
        Dblapostrophe,
        Hash,
        Dollar,
        Percent,
        Ampersand,
        Apostrophe,
        Leftparen,
        Rightparen,
        Asterisk,
        Plus,
        Comma,
        Minus,
        Period,
        Slash,
        _0,
        _1,
        _2,
        _3,
        _4,
        _5,
        _6,
        _7,
        _8,
        _9,
        Colon,
        Semicolon,
        Less,
        Equals,
        Greater,
        Question,
        At,
        Leftbracket,
        Backslash,
        Rightbracket,
        Caret,
        Underscore,
        Grave,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Leftbrace,
        Pipe,
        Rightbrace,
        Tilde,
        Delete,
        Plusminus,
        Capslock,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        Printscreen,
        Scrolllock,
        Pause,
        Insert,
        Home,
        Pageup,
        End,
        Pagedown,
        Right,
        Left,
        Down,
        Up,
        Numlockclear,
        LCtrl,
        LShift,
        LAlt,
        Rctrl,
        RShift,
        RAlt
    };

    enum class Button {
        Left,
        Middle,
        Right,
        X1,
        X2
    };

    unsigned int key_to_sdl_keycode(Key key);
    Key sdl_keycode_to_key(unsigned int keycode);

    int button_to_sdl_button(Button button);
    Button sdl_button_to_button(int button);
}
