import subprocess

KEY = R"data\models\board\board.objS"
ENCRYPTER = R"..\encrypter-helper\encrypter-helper.exe"
DATA = R"..\data"
SUFFIX = ".dat"


def encrypt(file: str):
    subprocess.run([ENCRYPTER, Rf"{DATA}\{file}", Rf"{DATA}\{file}{SUFFIX}", KEY])


encrypt(R"cursors\arrow.png")
encrypt(R"cursors\cross.png")

encrypt(R"models\board\board.obj")
encrypt(R"models\board\board_paint.obj")
encrypt(R"models\node\node.obj")
encrypt(R"models\piece\white_piece.obj")
encrypt(R"models\piece\black_piece.obj")

encrypt(R"shaders\internal\origin.vert")
encrypt(R"shaders\internal\origin.frag")
encrypt(R"shaders\internal\outline.vert")
encrypt(R"shaders\internal\outline.frag")
encrypt(R"shaders\internal\quad2d.vert")
encrypt(R"shaders\internal\quad2d.frag")
encrypt(R"shaders\internal\quad3d.vert")
encrypt(R"shaders\internal\quad3d.frag")
encrypt(R"shaders\internal\screen_quad.vert")
encrypt(R"shaders\internal\screen_quad.frag")
encrypt(R"shaders\internal\shadow.vert")
encrypt(R"shaders\internal\shadow.frag")
encrypt(R"shaders\internal\skybox.vert")
encrypt(R"shaders\internal\skybox.frag")
encrypt(R"shaders\internal\text.vert")
encrypt(R"shaders\internal\text.frag")
encrypt(R"shaders\board_paint.vert")
encrypt(R"shaders\board_paint.frag")
encrypt(R"shaders\board.vert")
encrypt(R"shaders\board.frag")
encrypt(R"shaders\node.vert")
encrypt(R"shaders\node.frag")
encrypt(R"shaders\piece.vert")
encrypt(R"shaders\piece.frag")

encrypt(R"textures\board\board_normal.png")
encrypt(R"textures\board\board_paint.png")
encrypt(R"textures\board\board_paint-small.png")
encrypt(R"textures\board\board_wood.png")
encrypt(R"textures\board\board_wood-small.png")
encrypt(R"textures\indicator\white_indicator.png")
encrypt(R"textures\indicator\black_indicator.png")
encrypt(R"textures\piece\piece_normal.png")
encrypt(R"textures\piece\white_piece.png")
encrypt(R"textures\piece\white_piece-small.png")
encrypt(R"textures\piece\black_piece.png")
encrypt(R"textures\piece\black_piece-small.png")
encrypt(R"textures\skybox\autumn\nx.png")
encrypt(R"textures\skybox\autumn\nx-small.png")
encrypt(R"textures\skybox\autumn\ny.png")
encrypt(R"textures\skybox\autumn\ny-small.png")
encrypt(R"textures\skybox\autumn\nz.png")
encrypt(R"textures\skybox\autumn\nz-small.png")
encrypt(R"textures\skybox\autumn\px.png")
encrypt(R"textures\skybox\autumn\px-small.png")
encrypt(R"textures\skybox\autumn\py.png")
encrypt(R"textures\skybox\autumn\py-small.png")
encrypt(R"textures\skybox\autumn\pz.png")
encrypt(R"textures\skybox\autumn\pz-small.png")
encrypt(R"textures\skybox\field\nx.png")
encrypt(R"textures\skybox\field\nx-small.png")
encrypt(R"textures\skybox\field\ny.png")
encrypt(R"textures\skybox\field\ny-small.png")
encrypt(R"textures\skybox\field\nz.png")
encrypt(R"textures\skybox\field\nz-small.png")
encrypt(R"textures\skybox\field\px.png")
encrypt(R"textures\skybox\field\px-small.png")
encrypt(R"textures\skybox\field\py.png")
encrypt(R"textures\skybox\field\py-small.png")
encrypt(R"textures\skybox\field\pz.png")
encrypt(R"textures\skybox\field\pz-small.png")
encrypt(R"textures\splash_screen\splash_screen.png")
