import subprocess

KEY = "data/models/board/board.obj" + "S"
ENCRYPTER = r"..\encrypter-helper\encrypter.exe"
DATA = r"..\data"
SUFFIX = ".dat"


def encrypt(file: str):
    subprocess.run([ENCRYPTER, rf"{DATA}\{file}", rf"{DATA}\{file}{SUFFIX}", KEY])


encrypt(r"cursors\arrow\arrow.png")
encrypt(r"cursors\cross\cross.png")

encrypt(r"models\board\board.obj")
encrypt(r"models\board\board_paint.obj")
encrypt(r"models\node\node.obj")
encrypt(r"models\piece\white_piece.obj")
encrypt(r"models\piece\black_piece.obj")

encrypt(r"shaders\internal\outline.vert")
encrypt(r"shaders\internal\outline.frag")
encrypt(r"shaders\internal\quad2d.vert")
encrypt(r"shaders\internal\quad2d.frag")
encrypt(r"shaders\internal\quad3d.vert")
encrypt(r"shaders\internal\quad3d.frag")
encrypt(r"shaders\internal\screen_quad.vert")
encrypt(r"shaders\internal\screen_quad.frag")
encrypt(r"shaders\internal\shadow.vert")
encrypt(r"shaders\internal\shadow.frag")
encrypt(r"shaders\internal\skybox.vert")
encrypt(r"shaders\internal\skybox.frag")
encrypt(r"shaders\internal\text.vert")
encrypt(r"shaders\internal\text.frag")
encrypt(r"shaders\board\board_paint.vert")
encrypt(r"shaders\board\board_paint.frag")
encrypt(r"shaders\board\board.vert")
encrypt(r"shaders\board\board.frag")
encrypt(r"shaders\board\board_paint_no_normal.vert")
encrypt(r"shaders\board\board_paint_no_normal.frag")
encrypt(r"shaders\board\board_no_normal.vert")
encrypt(r"shaders\board\board_no_normal.frag")
encrypt(r"shaders\node\node.vert")
encrypt(r"shaders\node\node.frag")
encrypt(r"shaders\piece\piece.vert")
encrypt(r"shaders\piece\piece.frag")
encrypt(r"shaders\piece\piece_no_normal.vert")
encrypt(r"shaders\piece\piece_no_normal.frag")

encrypt(r"shaders\post_processing\blur.vert")
encrypt(r"shaders\post_processing\blur.frag")
encrypt(r"shaders\post_processing\bright_filter.vert")
encrypt(r"shaders\post_processing\bright_filter.frag")
encrypt(r"shaders\post_processing\combine.vert")
encrypt(r"shaders\post_processing\combine.frag")

encrypt(r"textures\board\board_normal.png")
encrypt(r"textures\board\board_normal-small.png")
encrypt(r"textures\board\paint\board_paint.png")
encrypt(r"textures\board\paint\board_paint-small.png")
encrypt(r"textures\board\paint\board_paint_labeled.png")
encrypt(r"textures\board\paint\board_paint_labeled-small.png")
encrypt(r"textures\board\wood\board_wood.png")
encrypt(r"textures\board\wood\board_wood-small.png")
encrypt(r"textures\indicator\white_indicator.png")
encrypt(r"textures\indicator\black_indicator.png")
encrypt(r"textures\indicator\wait_indicator.png")
encrypt(r"textures\piece\piece_normal.png")
encrypt(r"textures\piece\piece_normal-small.png")
encrypt(r"textures\piece\white\white_piece.png")
encrypt(r"textures\piece\white\white_piece-small.png")
encrypt(r"textures\piece\black\black_piece.png")
encrypt(r"textures\piece\black\black_piece-small.png")
encrypt(r"textures\skybox\autumn\nx.png")
encrypt(r"textures\skybox\autumn\nx-small.png")
encrypt(r"textures\skybox\autumn\ny.png")
encrypt(r"textures\skybox\autumn\ny-small.png")
encrypt(r"textures\skybox\autumn\nz.png")
encrypt(r"textures\skybox\autumn\nz-small.png")
encrypt(r"textures\skybox\autumn\px.png")
encrypt(r"textures\skybox\autumn\px-small.png")
encrypt(r"textures\skybox\autumn\py.png")
encrypt(r"textures\skybox\autumn\py-small.png")
encrypt(r"textures\skybox\autumn\pz.png")
encrypt(r"textures\skybox\autumn\pz-small.png")
encrypt(r"textures\skybox\field\nx.png")
encrypt(r"textures\skybox\field\nx-small.png")
encrypt(r"textures\skybox\field\ny.png")
encrypt(r"textures\skybox\field\ny-small.png")
encrypt(r"textures\skybox\field\nz.png")
encrypt(r"textures\skybox\field\nz-small.png")
encrypt(r"textures\skybox\field\px.png")
encrypt(r"textures\skybox\field\px-small.png")
encrypt(r"textures\skybox\field\py.png")
encrypt(r"textures\skybox\field\py-small.png")
encrypt(r"textures\skybox\field\pz.png")
encrypt(r"textures\skybox\field\pz-small.png")
encrypt(r"textures\splash_screen\splash_screen.png")
encrypt(r"textures\splash_screen\launcher\launcher_splash_screen.png")
encrypt(r"textures\keyboard_controls\keyboard_controls.png")
encrypt(r"textures\keyboard_controls\keyboard_controls_cross.png")

print("Done")
